language: rust
git:
  quiet: true

rust:
  - stable

cache:
  - cargo
  - directories:
    - $HOME/Library/Caches/Homebrew

os:
  - windows
  - linux
  - osx

branches:
  only:
    - master

before_cache:
  - brew cleanup

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      # https://formulae.brew.sh/formula/sdl2#default
      brew install sdl2
    elif [ "$TRAVIS_OS_NAME" == "linux" ]
      # the package managers often have very old versions of SDL2, we just build
      # the correct version from source
      sudo ./build/install-sdl2.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" != "windows" ]
    then
      sdl2-config --cflags
      sdl2-config --libs
      sdl2-config --static-libs
    fi

script:
  - cargo build